- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
Add intel legal  files for Day 0.
> Add Intel files

- jclklib/README_jclklib.md
This document will provide basic architecture and simplified code flow for connect/subscribe/notification messages.
This is a live document.
> Doc: add README_jclklib.md

- jclklib/README_jclklib.md
This change is to add more details on the CONNECT message code flow. From client -> proxy and the reply as well.
> Doc: Added details on connect message code flow.

- .github/workflows/codeql.yml
Replace autobuild command with proper build steps
> Fix CodeQL build issue

- .github/workflows/virus_scan.yml
The virus scan will be run for every PR agaist master branch and whenever master branch got changes.
> Add new Github action for Virus Scan

- jclklib/TEST_jclklib.md
This document is created for clock manager installation and test guidance reference. Can be used by user and validation alike.
This is a live document. 
Signed-off-by: Noor Azura Ahmad Tarmizi <noor.azura.ahmad.tarmizi@intel.com>
> doc: Creation TEST_jclkib.md

- jclklib/proxy/run_ptp4l.sh
Execute the script with "sh ./run_ptp4l.sh" and start ptp4l program.
> Script: Start ptp4l program at proxy

- jclklib/client/subscribe_msg.cpp
- jclklib/common/jclklib_import.hpp
- jclklib/proxy/subscribe_msg.cpp
1. Ensure the CommonSubscribe parse and build is used.
2. Add peter changes  - 
Subscribe: Write the ptp4l event into client's struct
> Subscription update 

- jclklib/client/client_state.cpp
- jclklib/client/client_state.hpp
- jclklib/client/init.cpp
- jclklib/client/init.hpp
- jclklib/client/notification_msg.cpp
- jclklib/client/subscribe_msg.cpp
- jclklib/client/subscribe_msg.hpp
- jclklib/client/test.cpp
- jclklib/common/jclklib_import.hpp
- jclklib/common/subscribe_msg.hpp
- jclklib/proxy/connect_msg.cpp
- jclklib/proxy/thread.cpp
Complete subscription flow with current state given. The timeout is 5 sec.
> feature: subscribe api with current state given

- jclklib/client/init.cpp
- jclklib/client/notification_msg.cpp
- jclklib/client/test.cpp
remove additional debug print for better view on the result.
> jclklib: remove debug printing

- jclklib/client/init.cpp
- jclklib/client/notification_msg.cpp
Reset the event_count after status_wait.
> fix event_count after status_wait

- jclklib/client/notification_msg.cpp
- jclklib/client/subscribe_msg.cpp
The jcl_state data and event_count are updating based on event that subscribed.
Below shown the result that:
1. only subscribed gmOffsetEvent and servoLockedEvent, hence only these 2 events data being updated:
2. only subscribed gmOffsetEvent, gmPresentEvent and gmChangedEvent, hence only these 3 events data being updated:
> jclklib: Add subscribed event checking

- jclklib/client/test.cpp
improve printing of data receive by test app for better readability.
> jclklib: improve printing in test app

- jclklib/client/notification_msg.cpp
- jclklib/client/subscribe_msg.cpp
Fix incorrect composite status check in subscribe and notify msg.
> jclklib: Fix incorrect composite status

- jclklib/proxy/thread.cpp
- jclklib/proxy/thread.hpp
Code cleanup and remove those unused function.
> Code cleanup for thread.cpp and thread.hpp

- jclklib/client/test.cpp
- json/jsonFrom.cpp
- pub/msg.h
- src/msg.cpp
- src/proc.cpp
- src/proc.m4
- uctest/json2msg.c
- uctest/msg2json.c
- uctest/proc.c
- utest/json2msg.cpp
- utest/msg2json.cpp
- utest/pmc_dump.cpp
- utest/proc.cpp
Fix following error check in CI:
Check: jclklib/client/test.cpp:211: for wrong char: jcl_disconnect();
> Fix Continuous Integration check failure

- jclklib/client/test.cpp
Allow user to input upper and lower limit for master offset.
> jclklib: test: add upper and lower limit for master offset

- .github/workflows/codeql.yml
- .github/workflows/coverity.yml
check coverity for jclklib since make is separated
> CI: move coverity to jclklib folder

- jclklib/client/Makefile
- jclklib/client/client_state.cpp
- jclklib/client/client_state.hpp
- jclklib/client/connect_msg.cpp
- jclklib/client/connect_msg.hpp
- jclklib/client/init.cpp
- jclklib/client/init.hpp
- jclklib/client/msgq_tport.cpp
- jclklib/client/notification_msg.cpp
- jclklib/client/notification_msg.hpp
- jclklib/client/subscribe_msg.cpp
- jclklib/client/subscribe_msg.hpp
- jclklib/client/test.cpp
- jclklib/common/message.cpp
- jclklib/common/notification_msg.hpp
- jclklib/proxy/connect.cpp
- jclklib/proxy/connect_msg.cpp
> client data management: Regroup the client data accordingly.

- jclklib/client/notification_msg.cpp
Fix unnnessary increment of event count
> jclklib: fix event count issue for composite event

- jclklib/client/client_state.cpp
- jclklib/client/init.cpp
- jclklib/client/notification_msg.cpp
- jclklib/client/subscribe_msg.cpp
- jclklib/client/test.cpp
- jclklib/common/jclklib_import.hpp
- jclklib/proxy/connect.cpp
- jclklib/proxy/thread.hpp
The gm_present event is no longer available:
1. On client:
2. On proxy
> Remove gm_present event

- jclklib/proxy/client.hpp
- jclklib/proxy/connect.cpp
Send notification to all clients.
> jclklib: proxy: Add multi client notification support

- jclklib/client/Makefile
- jclklib/client/init.cpp
- jclklib/client/msgq_tport.cpp
- jclklib/client/subscribe_msg.cpp
- jclklib/client/test.cpp
- jclklib/common/Makefile
- jclklib/proxy/Makefile
- jclklib/proxy/connect.cpp
> Remove debug printing

- jclklib/client/msgq_tport.cpp
- jclklib/common/print.cpp
- jclklib/proxy/connect.cpp
- jclklib/proxy/msgq_tport.cpp
Proxy will notify the user whether it able to connect to ptp4l or not:
> Fix proxy not able to reconnect to ptp4l issue

- jclklib/TEST_jclklib.md
- jclklib/sample/jclk_test.cpp
Add idle time to represent user app busying handle other task.
> jclklib: sample: Add idle time argument

- jclklib/client/jclk_init.cpp
- jclklib/proxy/connect_msg.cpp
- jclklib/sample/jclk_test.cpp
Check whether Proxy still alive by sending connect msg and wait for response.
> jclklib: Add Proxy message queue liveness check

- jclklib/sample/jclk_test.cpp
> Fix build error

- Makefile
To run : make format V=1 
There is other files to changes still
> Format check alignment 

- clkmgr/README_clkmgr.md
- clkmgr/client/client_state.cpp
- clkmgr/client/clockmanager.cpp
- clkmgr/client/clockmanager_c.cpp
- clkmgr/client/msgq_tport.cpp
- clkmgr/client/notification_msg.cpp
- clkmgr/client/subscribe_msg.cpp
- clkmgr/client/subscribe_msg.hpp
- clkmgr/common/ptp_event.hpp
- clkmgr/common/subscribe_msg.cpp
- clkmgr/common/subscribe_msg.hpp
- clkmgr/common/subscription.cpp
- clkmgr/proxy/subscribe_msg.cpp
- clkmgr/pub/clkmgr/client_state.h
- clkmgr/pub/clkmgr/clockmanager_c.h
- clkmgr/pub/clkmgr/event_state.h
- clkmgr/pub/clkmgr/subscription.h
- clkmgr/pub/clkmgr/utility.h
- clkmgr/pub/clockmanager.h
- clkmgr/sample/clkmgr_c_test.c
- clkmgr/sample/clkmgr_test.cpp
This commit refactors the Clock Manager library to improve the C++ and C APIs and enhance documentation to make the Clock Manager library more maintainable, type-safe, and understandable for future development:
-  Updated public header files to use modern C++ practices, including `std::array` for fixed-size arrays and default member initializations.
-  Added and improved Doxygen comments for better clarity and consistency across the codebase.
-  Ensured consistent naming conventions and coding style in `clockmanager.hpp` and `clockmanager_c.h`.
-  Enhanced readability and maintainability by following best practices for C and C++ coding styles.
> Improve APIs, enhance documentation and add make install support

- clkmgr/sample/clkmgr_c_test.c
- clkmgr/sample/clkmgr_test.cpp
This patch renames several variables in the clkmgr module to improve clarity and consistency.
These changes enhance the readability and maintainability of the code by using more descriptive and consistent variable names.
> clkmgr: Sample apps improvement

- clkmgr/TEST_clkmgr.md
- clkmgr/sample/clkmgr_c_test.c
- clkmgr/sample/clkmgr_test.cpp
1. Update librtpi repo and librtpi compilation steps in TEST_clkmgr.md file
2. Update C/C++ sample apps for GM_UUID printing for more clarity
New sample apps printing for GM_UUID:
> clkmgr: Update librtpi repo.

- clkmgr/client/client_state.cpp
- clkmgr/client/client_state.hpp
- clkmgr/proxy/subscribe_msg.cpp
MAximum value of domain number is 255, thus change to use uint8_t.
> clkmgr: change domainNumber type to uint8_t.

- clkmgr/HLD_clkmgr.md
- clkmgr/client/clockmanager_c.cpp
- clkmgr/pub/clkmgr/clockmanager_c.h
- clkmgr/sample/clkmgr_c_test.c
Added C wrapper to set and get UDS addresses for ptp4l and chrony instances.
> [WIP] clkmgr: Add C wrapper for setting UDS addr for ptp4l and chrony instances

- clkmgr/client/clockmanager.cpp
- clkmgr/client/clockmanager_c.cpp
- clkmgr/pub/clockmanager.h
- clkmgr/sample/clkmgr_c_test.c
- clkmgr/sample/clkmgr_test.cpp
- Enable dynamic UDS addrress for ptp4l and chrony
- Enable dynamic domainNumber for ptp4l
> clkmgr: Add support for dynamic UDS for sample app

- clkmgr/proxy/connect_chrony.cpp
- clkmgr/proxy/connect_chrony.hpp
- clkmgr/proxy/connect_msg.cpp
- clkmgr/proxy/connect_ptp4l.cpp
- clkmgr/proxy/connect_ptp4l.hpp
- clkmgr/proxy/main.cpp
- clkmgr/proxy/notification_msg.cpp
- clkmgr/proxy/notification_msg.hpp
- clkmgr/proxy/subscribe_msg.cpp
- clkmgr/proxy/subscribe_msg.hpp
Tested by running 2 ptp4l with different domains and two chrony:
1. Subscription event data
2. Notification event data
> clkmgr: Add support for multidomain ptp4l.

- clkmgr/common/transport.cpp
- clkmgr/common/transport.hpp
- clkmgr/common/util.hpp
- clkmgr/proxy/connect_ptp4l.cpp
- clkmgr/proxy/notification_msg.hpp
- clkmgr/proxy/subscribe_msg.hpp
- src/jsonParser.cpp
- src/jsonParser.h
- src/proc.cpp
- src/sig.cpp
- tools/ci_address.sh
1. Subscription event:
2. Notification event:
> Add Erez's patches

- clkmgr/proxy/connect_chrony.cpp
This commit refactors the subscribe_to_chronyd function:
- Replaced the loop that processes chrony fields with direct field index lookups using chrony_get_field_index.
- Removed the unused variable 'content' and redundant code.
- Simplified the logic for extracting and storing the 'reference ID', 'poll', and 'original last sample offset' fields.
Tested with 2 chrony daemon running and sample app subscribe to each index:
Printout from proxy shows proxy able to retrieve chrony data from both chrony daemon:
> clkmgr: Update to new libchrony API.

- clkmgr/sample/clkmgr_test.cpp
For single domain demo purpose only.
> clkmgr: Demo - Single Domain

- clkmgr/HLD_clkmgr.md
Update the HLD documentation for multi-domain support
> clkmgr: Update HLD for multi-domain support.

- clkmgr/HLD_clkmgr.md
- clkmgr/README.md
- clkmgr/TEST_clkmgr.md
- clkmgr/sample/clkmgr_c_test.c
- clkmgr/sample/clkmgr_test.cpp
Update the documentation for multi-domain support
> [WIP] clkmgr: Update documentation for multi-domain support.

- clkmgr/client/clockmanager.cpp
- clkmgr/client/clockmanager_c.cpp
- clkmgr/client/timebase_state.cpp
- clkmgr/client/timebase_state.hpp
- clkmgr/common/clock_event.cpp
- clkmgr/common/clock_event_handler.hpp
- clkmgr/pub/clkmgr/event.h
- clkmgr/pub/clockmanager.h
- clkmgr/sample/clkmgr_test.cpp
1. during subscribe:  
2. during notification:
> clkmgr: modulate clock event for backward compatibility

- clkmgr/client/timebase_state.cpp
- clkmgr/client/timebase_state.hpp
<h1>Suggested PR Title - Remove Unused Code and Simplify TimeBaseState Implementation in clkmgr</h1>
- Removed the `toString` method from `timebase_state.cpp` and its declaration from `timebase_state.hpp`.
- Removed the `Event_state` member from the `TimeBaseState` class, as it was not utilized.
- Cleaned up related comments and code to reflect these changes.
Tested functionality working fine:
code_improvement
___
- Removed the unused toString method from timebase_state.cpp and its declaration from timebase_state.hpp.
- Removed the Event_state member from the TimeBaseState class in timebase_state.hpp, streamlining the class structure.
- …
> clkmgr: Remove unused variable.

- clkmgr/client/subscription.cpp
- clkmgr/client/timebase_state.cpp
- clkmgr/client/timebase_state.hpp
- clkmgr/common/types.m4
- clkmgr/pub/clkmgr/subscription.h
- clkmgr/utest/subscription.cpp
<h1>Suggested PR Title - Enhance event mask validation and error handling in clkmgr module</h1>
- Change setEventMask and setCompositeEventMask to return bool for error checking.
- Add validation to ensure event masks do not exceed defined event bits.
- Update TimeBaseState and TimeBaseStates to propagate subscription set success/failure.
- Update unit tests to check for correct mask validation and error handling.
- Improve documentation for mask-related APIs.
- Add COMPOSITE_EVENT_ALL constant to types.m4 for composite event validation.
code_enhancement, issue_resolution
___
- Updated setEventMask and setCompositeEventMask across …
> clkmgr: Improve event mask validation in subscription logic

- clkmgr/utest/client_state.cpp
- clkmgr/utest/subscription.cpp
Update unit test for client state and subscription.
> clkmgr: Update unit test for client state and subscription.

- clkmgr/TEST_clkmgr.md
- clkmgr/client/timebase_state.cpp
- clkmgr/sample/clkmgr_c_test.c
- clkmgr/sample/clkmgr_test.cpp
- clkmgr/sample/run_clkmgr_c_test.sh
- clkmgr/sample/run_clkmgr_test.sh
- wrappers/go/clkmgr_gtest/clkmgr_gtest.go
- wrappers/lua/clkmgr_test.lua
- wrappers/perl/clkmgr_test.pl
- wrappers/php/clkmgr_test.php
- wrappers/python/clkmgr_test.py
- wrappers/ruby/clkmgr_test.rb
- wrappers/tcl/clkmgr_test.tcl
<h1>Suggested PR Title - Enhance clkmgr sample applications with detailed event printouts and update documentation</h1>
- Added new printout function for both subscription and notification
- Update md file with the printing
1. Tested with C++ sample apps:
2. Tested with C sample apps:
code_enhancement, feature_enhancement
___
- Added a new function to set notification timestamps in TimeBaseStates.
- Enhanced the C++ sample application in clkmgr_test.cpp with new event handling, a detailed printout function for better debugging and visualization of clock events, and refactoring to use this new function.
- Updated the C sample application …
> clkmgr: Refactor sample apps

- clkmgr/proxy/client.hpp
- clkmgr/utest/Makefile
- clkmgr/utest/client.cpp
Add unit test for Client class and fix typo for getPTPEvent( ).
Test Results:
> Add unit test for Client class

- clkmgr/proxy/client.cpp
- clkmgr/proxy/client.hpp
- clkmgr/proxy/connect_ptp4l.cpp
- clkmgr/utest/Makefile
- clkmgr/utest/client.cpp
1. Add unit test for Client class.
2. Refactor port handling and event initialization
> clkmgr: Add unit test for Client class & Refactor port handling and event initialization .

- .github/dependent_files.json
- .github/workflows/CODE_REVIEW_REPORT.yml
- .github/workflows/DEVELOPER_ASSISTANT.yaml
- .github/workflows/build_gentoo.yml
- .github/workflows/coverity.yml
- .github/workflows/coverity_clang.yml
- .github/workflows/doc.yml
- .github/workflows/virus_scan.yml
- README.md
- clkmgr/sample/clkmgr_test.cpp
- doc/CODE_OF_CONDUCT.md
- doc/CONTRIBUTING.md
- doc/SECURITY.md
> clkmgr: Fix timeout value display in help message.

- clkmgr/proxy/connect_ptp4l.cpp
Changes List:
- Adds a dedicated callback for `LOG_SYNC_INTERVAL` to retrieve syncInterval.
- Updates logic in `CMLDS_INFO_NP` callback to ignore `CMLDS_INFO_NP` messages from peer portNumber 0, ensuring asCapable accurately reflects the current state.
- Requests `LOG_SYNC_INTERVAL` on initial connection so the client receives the correct syncInterval value.
> clkmgr: Fix asCapable incorrect event count.

- clkmgr/client/timebase_state.cpp
- clkmgr/sample/clkmgr_c_test.c
- clkmgr/sample/clkmgr_test.cpp
- wrappers/go/clkmgr_gtest/clkmgr_gtest.go
- wrappers/perl/clkmgr_test.pl
- wrappers/php/clkmgr_test.php
- wrappers/python/clkmgr_test.py
- wrappers/ruby/clkmgr_test.rb
- wrappers/tcl/clkmgr_test.tcl
> clkmgr: Print PTP-related info only when PTP data is available
