intel-staging/libptpmgmt_iaclocklib

jclklib/client/client_state.cpp
jclklib/client/client_state.hpp
jclklib/client/connect_msg.cpp
jclklib/client/connect_msg.hpp
jclklib/client/init.cpp
jclklib/client/test.cpp
jclklib/common/connect_msg.cpp
jclklib/common/util.hpp

The connect message now will return the client session ID to the client. It will also have the timeout of 5 sec by default to receive the proxy reply.
This could be changed in the future.

Feature: Complete the connect msg path with timeout

---

jclklib/client/connect_msg.cpp
jclklib/client/connect_msg.hpp
jclklib/client/subscribe_msg.cpp
jclklib/common/jclklib_import.hpp
jclklib/proxy/connect.cpp
jclklib/proxy/connect_msg.cpp
jclklib/proxy/connect_msg.hpp
jclklib/proxy/thread.cpp

1. Client is receiving ptp4l_id once proxy is connected to ptp4l
2. Client will getting connection failed if proxy is not connected to ptp4l

Connect: Send ptp4l_id from Proxy to Client once ptp4l is connected

---

jclklib/client/init.cpp
jclklib/client/init.hpp
jclklib/client/test.cpp

Now, jcl_status_wait() will waits for a specified timeout period for any event changes.

jclklib: Add timeout support in jcl_status_wait() API

---

jclklib/client/init.cpp
jclklib/client/notification_msg.cpp
jclklib/client/subscribe_msg.cpp
jclklib/client/test.cpp
jclklib/common/jclklib_import.hpp

Allow user to set composite event where they will only be notified whether all events are meet or at least one of the event is not meet.

jclklib: Add composite event support

---

jclklib/common/msgq_tport.cpp
jclklib/proxy/msgq_tport.cpp

Fix the issue that proxy is hang after client is terminated.
1. When client is terminated, proxy will return error:
2. When client started again, the proxy is able to send the notification msg to client:

jclklib: Fix proxy hang issue after client is terminated

---

jclklib/client/test.cpp

Allow user to input hex value to mask with 0x or 0X prefix.
Besides, print out the unit for timeout and upper lower limit.

jclklib: test: Add hex support to mask input

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
SECURITY.md
jclklib/README_jclklib.md
jclklib/TEST_jclklib.md

Add GFDL-1.3-no-invariants-or-later license header to all md documentation files.

Add license header to md

---

jclklib/TEST_jclklib.md

In new code base, autoheader is needed.

jclklib: update new build steps in latest libptpmgmt code base

---

jclklib/client/init.cpp
jclklib/client/subscribe_msg.cpp

The event count is updated properly and the event_count shouldn't keep decreasing when master is terminated.

Fix event count not updated properly

---

jclklib/client/jclk_init.cpp

This commit adds a null check for the dynamic cast of `connectMsg.get()` to `ClientConnectMessage` in the `check_proxy_liveness` function.
Previously, if the dynamic cast failed, the program would attempt to dereference a null pointer, leading to undefined behavior. With this change, if the dynamic cast fails, the function will print a debug message and return false, preventing the null pointer dereference.

Add null check for dynamic cast in check_proxy_liveness

---

jclklib/client/jclk_client_state.cpp
jclklib/client/jclk_client_state.hpp
jclklib/client/jclk_init.cpp
jclklib/client/notification_msg.cpp

Steps to generate high load condition
1. add summary_interval -7 and logSyncInterval -7 in config file to make the ptp4l send more offset value in every second
2. remove sleep(idle_time) in sample/jclk_test.cpp to remove the wait time for the sample application
Tested with this patch and no client terminate issue observed under high load condition for long time.

jclklib: Fix client terminate under high load condition

---

.reuse/dep5
Makefile
jclklib/TEST_jclklib.md
jclklib/client/jclk_client_state.cpp
jclklib/client/jclk_client_state.hpp
jclklib/client/jclk_init.cpp
jclklib/client/jclklib_client_api_c.cpp
jclklib/client/jclklib_client_api_c.h
jclklib/client/notification_msg.cpp
jclklib/client/subscribe_msg.cpp
jclklib/common/jclklib_import.hpp
jclklib/proxy/connect_ptp4l.cpp
jclklib/proxy/thread.hpp
jclklib/sample/jclk_c_test.c
jclklib/sample/jclk_test.cpp
ptp-tools/pmc_dump.cpp
src/json.cpp
src/proc.cpp
src/proc.m4
uctest/json2msg.c
uctest/msg2json.c
uctest/proc.c
utest/json2msg.cpp
utest/msg2json.cpp
utest/pmc_dump.cpp
utest/proc.cpp

The previous implementation extracted the `servo_state` and used it to determine the `servo_locked` status. This has been refactored to directly use the `portState` to set `servo_locked`.

jclklib: Refactor servo lock status assignment in event_handle

---

jclklib/proxy/connect_ptp4l.cpp
jclklib/proxy/connect_ptp4l.hpp
jclklib/proxy/main.cpp

- Implemented the disconnect function in the Connect class.
- The function closes the obj and sk objects to properly release resources.
- Ensures that connections are properly terminated when disconnect is called.
Jira: https://jira.devtools.intel.com/browse/IOTGREALTJ-251

jclklib: Add disconnect function to Connect class

---

jclklib/client/jclk_init.cpp
jclklib/client/jclklib_client_api_c.cpp
jclklib/client/notification_msg.cpp
jclklib/client/subscribe_msg.cpp
jclklib/common/msgq_tport.cpp
jclklib/common/util.hpp
jclklib/proxy/msgq_tport.cpp
jclklib/sample/jclk_c_test.c
jclklib/sample/jclk_test.cpp
pub/c/jclklib_client_api_c.h
pub/jclk_client_state.hpp

It would be useful for the user to be able to get the GM offset from ptp4l to determine how well synchronized we are to the GM
Add offset from GM to state
Change code to update state even if no event occurs
Move some constants into util.h
Sample apps output:

Add offset to state, initial

---

clkmgr/client/clkmgr_client_api_c.cpp
clkmgr/client/notification_msg.cpp
clkmgr/client/subscribe_msg.cpp
pub/c/clkmgr_client_api_c.h
pub/clkmgr_client_state.hpp

clkmgr: Change notification timestamp type to uint64_t representing nanoseconds since the epoch.
clkmgr: When using the C API, update client state after wait whether or not an event occurs

clkmgr: Change notification timestamp type and update state when using the C api

---

clkmgr/TEST_clkmgr.md
clkmgr/client/clockmanager.cpp
clkmgr/client/notification_msg.cpp
clkmgr/client/subscribe_msg.cpp
clkmgr/sample/clkmgr_c_test.c
clkmgr/sample/clkmgr_test.cpp

The update timestamp currently use CLOCK_MONOTONIC. This cannot be used to correlate events on multiple devices. An example use case, is using Grafana to show how well devices in a cluster are synchronized. CLOCK_REALTIME is synced and can be used to correlate events across multiple devices.

clkmgr: Change to CLOCK_REALTIME for update timestamp

---

clkmgr/common/message.hpp
clkmgr/common/transport.hpp
clkmgr/proxy/connect_ptp4l.cpp
clkmgr/pub/clkmgr/client_state.h
clkmgr/pub/clkmgr/subscription.h
clkmgr/pub/clkmgr/utility.h

Refactor the event handling logic to improve readability and maintainability. This includes:
- Replacing raw pointer casts with static_cast for type safety.
- Consolidating the handling of TIME_STATUS_NP and PORT_DATA_SET events.
- Adding support to set the own clock identity as GM identity when the port state is MASTER.
- Ensuring that the master offset and GM identity are reset when the port state is PASSIVE or lower.
- Simplifying the logic for setting the synced_to_primary_clock flag based on the port state.
- Adding comments for clarity and debugging purposes.

clkmgr: Refactor event handling and add support for GM identity.

---

clkmgr/client/notification_msg.cpp
clkmgr/client/subscribe_msg.cpp

Fix the issue that incorrect gm_changed event status when restarting GM PTP4L on Host system.
Jira link: https://jira.devtools.intel.com/browse/IOTGREALTJ-255
Tested with gm_changed event is updated correctly when there is GM changed with UUID update:

clkmgr: Fix Incorrect gm_changed event status.

---

clkmgr/client/client_state.cpp
clkmgr/client/client_state.hpp
clkmgr/client/clockmanager.cpp
clkmgr/client/subscribe_msg.cpp
clkmgr/client/subscribe_msg.hpp
clkmgr/proxy/subscribe_msg.cpp
clkmgr/proxy/subscribe_msg.hpp
clkmgr/pub/clkmgr/utility.h
clkmgr/pub/clockmanager.h
clkmgr/sample/clkmgr_test.cpp

- Added methods to `ClientState` class to set and get UDS addresses for ptp4l and chrony instances.
- Updated `ClockManager` class to include methods for adding ptp4l and chrony instances with UDS addresses.
- Modified `ClientSubscribeMessage` and `ProxySubscribeMessage` classes to handle UDS addresses in the message buffer.
- Updated `clkmgr_test.cpp` to set ptp4l and chrony UDS addresses to `/var/run/ptp4l` and `/var/run/chrony/chronyd.sock` respectively.

clkmgr: Add support for setting UDS addr for ptp4l and chrony instances.

---

clkmgr/client/connect_msg.cpp
clkmgr/proxy/connect_chrony.cpp
clkmgr/proxy/connect_chrony.hpp
clkmgr/proxy/connect_msg.cpp
clkmgr/proxy/connect_ptp4l.cpp
clkmgr/proxy/connect_ptp4l.hpp
clkmgr/proxy/main.cpp
clkmgr/proxy/subscribe_msg.cpp

This patch enhances the clkmgr by adding support for dynamic Unix Domain Socket (UDS) addresses and domain numbers for ptp4l and chrony.
Tested with ptp4l and chrony running:

clkmgr: Add support for dynamic UDS address for ptp4l and chrony.

---

clkmgr/HLD_clkmgr.md
clkmgr/client/clockmanager.cpp
clkmgr/client/clockmanager_c.cpp
clkmgr/pub/clkmgr/clockmanager_c.h
clkmgr/pub/clockmanager.h
clkmgr/sample/clkmgr_c_test.c
clkmgr/sample/clkmgr_test.cpp

Add API for clkmgr_gettime() to retrieve time of the specified clock clk_id.

clkmgr: Add API for clkmgr_gettime()

---

clkmgr/common/ptp_event.hpp
clkmgr/proxy/connect_ptp4l.cpp
clkmgr/proxy/connect_ptp4l.hpp
clkmgr/proxy/notification_msg.cpp
clkmgr/proxy/notification_msg.hpp
clkmgr/proxy/subscribe_msg.cpp

This patch enhances the clkmgr by adding support for multiple domains in ptp4l and session-based event handling.
- Updated `ptp_event` structure to include `domain_number` and `session_id` fields.
- Modified `connect_ptp4l` function to accept `sessionId` and handle multiple domains.
- Implemented session-based event handling in `notify_client` and `event_handle` functions.
- Updated `ProxyNotificationMessage` to include `setSessionId` and `getSessionId` methods.
- Adjusted `makeBuffer` function in `ProxyNotificationMessage` to handle session-specific `ptp_event` data.
- Ensured proper initialization and usage of `ptp_event_map` to store and retrieve `ptp_event` data based on domain and session.
1. Tested by running 2 sample apps, and both subscribe each one domain number (left: domain 1, …

clkmgr: Add multi-domain support for ptp4l and session-based event handling.

---

clkmgr/proxy/connect_chrony.cpp

These changes ensure that the correct fields are identified and processed when subscribing to Chrony events.
1. Tested by running sample apps with 2 chrony daemon:
2. Proxy printout chrony data (reference id, offset, pool interval) for 2 chrony daemon:

clkmgr: Update Chrony's field name to latest libchrony.

---

clkmgr/client/clockmanager.cpp
clkmgr/client/clockmanager_c.cpp
clkmgr/client/connect_msg.cpp
clkmgr/client/subscribe_msg.cpp
clkmgr/client/subscribe_msg.hpp
clkmgr/proxy/connect_msg.cpp
clkmgr/proxy/subscribe_msg.cpp
clkmgr/proxy/subscribe_msg.hpp
clkmgr/pub/clkmgr/clockmanager_c.h
clkmgr/pub/clockmanager.h
clkmgr/sample/clkmgr_c_test.c
clkmgr/sample/clkmgr_test.cpp

This commit introduces the handling and parsing of the timeBaseIndex in the ClkMgrSubscription class.
- Added timeBaseIndex member to ClkMgrSubscription class.
- Implemented getter and setter methods for timeBaseIndex in ClkMgrSubscription.
- Updated ClockManager::clkmgr_subscribe to accept and set timeBaseIndex.
- Modified ClientSubscribeMessage and CommonSubscribeMessage to handle timeBaseIndex.
- Updated the parsing and serialization logic in connect_msg.cpp and subscribe_msg.cpp to include timeBaseIndex.
- Adjusted the clkmgr_test.cpp to use the new clkmgr_subscribe method with timeBaseIndex.
Tested with 2 sample apps each subscribe to one domain of ptp4l.
1. Subscription: 
2. Notification:

clkmgr: Add timeBaseIndex handling and parsing in ClkMgrSubscription.

---

clkmgr/proxy/connect_chrony.cpp
clkmgr/proxy/connect_chrony.hpp
clkmgr/proxy/connect_ptp4l.cpp
clkmgr/proxy/connect_ptp4l.hpp

These changes ensure that the session IDs are properly removed from the subscribed clients list when a message transmission fails, improving the robustness of the sample applications.

clkmgr: Add unsubscibe session id functionality for ptp4l and chrony

---

clkmgr/proxy/config_parser.cpp
clkmgr/proxy/proxy_cfg.json

Fix typo for timeBase to timeBases on config_parser and JSON file
Proxy:
Sample App:

clkmgr: Fix typo on config_parser and JSON file

---

clkmgr/client/client_state.hpp
clkmgr/common/util.hpp
clkmgr/pub/clkmgr/utility.h

Moved the definitions of TRANSPORT_CLIENTID_LENGTH, TransportClientId, sessionId_t, and InvalidSessionId from clkmgr/pub/clkmgr/utility.h to clkmgr/common/util.hpp, because these parameters are transparent to user application.

clkmgr: Move utility definitions from pub to common.

---

clkmgr/proxy/connect_chrony.cpp
clkmgr/proxy/connect_ptp4l.cpp

- Updated the monitor_chronyd function to use the udsAddrChrony from ThreadArgs for reconnection attempts.
- Simplified the reconnection logic by refactoring it into a separate function.
chrony data is reset if chronyd is terminated:
proxy able reconnect to chronyd again and able to get the chrony data:
clkmgr manage to connect to chronyd if chronyd is run after proxy (flow: start proxy -> sample apps -> chronyd)

clkmgr Refactor chrony connection handling and improve reconnection logic

---

clkmgr/client/clockmanager.cpp
clkmgr/client/clockmanager_c.cpp
clkmgr/pub/clkmgr/clockmanager_c.h
clkmgr/pub/clockmanager.h

This patch introduces the ability to subscribe to time base events using the time base name instead of the index. The following changes have been made:
- Added `clkmgr_subscribe_by_name` and `clkmgr_status_wait_by_name` methods to the `ClockManager` class.
- Implemented corresponding C functions `clkmgr_c_subscribe_by_name` and `clkmgr_c_status_wait_by_name`.
These changes enhance the flexibility of the clock manager by allowing users to monitor time bases by name, making the interface more user-friendly.
C++:
C:

clkmgr:Add support for subscribing to time base by name.

---

clkmgr/client/timebase_state.cpp
clkmgr/proxy/config_parser.cpp
clkmgr/proxy/connect_ptp4l.cpp

Tested gm_changed status is updated as expected when gm is disconnected and restart again:
Jira ticket: https://jira.devtools.intel.com/browse/IOTGREALTJ-255

Fix gm_changed event status and coverity issue

---

clkmgr/proxy/connect_ptp4l.cpp

Using constant reference as function parameter allow
calling with r-value, but do not copy,
though eliminate the need to move.
In class ptpSet in connect_ptp4l.cpp,
convert udsAddr to reference, so we skip 1 copy and 1 move.
Tested working as expected:

clkmgr: replace the use of move with constant reference.

---

clkmgr/TEST_clkmgr.md
clkmgr/client/clockmanager.cpp
clkmgr/proxy/main.cpp
clkmgr/proxy/run_proxy.sh

This patch enhances the `check_proxy_liveness` function by introducing a static `lastConnectTime` variable to track the last successful connection time.
- Added a check to compare the time elapsed since the last connection with the default liveness timeout.
- Updated the logic to store the last connection time using `clock_gettime` upon receiving a reply from the proxy.

clkmgr: Improve proxy liveness check with last connect time tracking.

---

clkmgr/client/clockmanager.cpp
clkmgr/client/clockmanager_c.cpp
clkmgr/client/timebase_state.cpp
clkmgr/common/ptp_event.hpp
clkmgr/common/types.m4
clkmgr/proxy/connect_ptp4l.cpp
clkmgr/sample/clkmgr_c_test.c
clkmgr/sample/clkmgr_test.cpp

This patch introduces functionality to retrieve the `logSyncInterval` from the
ptp4l daemon and display it in the clkmgr system. The changes include:
- Remove `PORT_PROPERTIES_NP`.
- Modified the `PORT_DATA_SET` callback to handle different event.
- `logSyncInterval` is retrieved from ptp4l daemon and stored in the `event`
structure.
- Introduce reset_PortDataSet() to consolidate all the action to reset
the related port data.
- Modified the test application to display the `gm_logSyncInterval`
These changes improve the visibility of the Grandmaster's `logSyncInterval`
so that the behavior is transparent and controllable in the clkmgr system.

clkmgr: Add support for retrieve logSyncInterval from ptp4l.

---

clkmgr/client/connect_msg.cpp
clkmgr/common/msgq_tport.cpp
clkmgr/common/msgq_tport.hpp
clkmgr/proxy/connect_chrony.cpp
clkmgr/proxy/connect_ptp4l.cpp

1. Fix - clkmgr: Fix sessionId not properly removed for ptp4l and Chrony.
**Description:**
ptp4l:
The unsubscribed session may subscribed to multiple ptpSets (timeBaseIndex).
Therefore, proxy should remove the sessionId from all ptpSets that the session
subscribed to before remove the sessionId from the SessionMap.
Chrony:
The unsubscribed session may subscribed to multiple ChronyThreadSet (timeBaseIndex).
Therefore, proxy should remove the sessionId from all ChronyThreadSet that the
session subscribed to before remove the sessionId from the SessionMap.
In addition, this fix maintains the consistency of ptp4l and Chrony's unsubscribed
behavior.
2. clkmgr: Add Listener's getClientId() method
**Description:**
Introduce `getClientId()` method so that client can put it into
`CONNECT_MSG` …

clkmgr: Reset buffer offset before handle new message in MqListenerWork

---

clkmgr/client/clockmanager.cpp
clkmgr/client/clockmanager_c.cpp
clkmgr/client/timebase_state.cpp
clkmgr/client/timebase_state.hpp
clkmgr/common/clock_event_handler.hpp
clkmgr/common/subscribe_msg.cpp
clkmgr/common/subscribe_msg.hpp
clkmgr/common/subscription.cpp
clkmgr/common/types.m4
clkmgr/pub/clkmgr/clockmanager_c.h
clkmgr/pub/clkmgr/subscription.h
clkmgr/pub/clockmanager.h
clkmgr/sample/clkmgr_c_test.c
clkmgr/sample/clkmgr_test.cpp

<h1>Suggested PR Title - Refactor ClockManager Subscription Handling to Use New Subscription Classes</h1>
This patch refactors the subscription handling mechanism within the ClockManager module.
The changes include:
- Replacing the ClkMgrSubscription with ClockSyncSubscription in the subscribe and subscribeByName methods to encapsulate both PTP and SysClock subscriptions.
- Updating the TimeBaseState and TimeBaseStates classes to separately manage PTP and SysClock event subscriptions.
- Modifying the subscription logic to handle composite event masks specifically for PTP subscriptions.
- Adjusting the clkmgr_test sample application to utilize the new ClockSyncSubscription class for subscribing to time base indices.
- Removing unused code and comments related to the previous subscription …

clkmgr: Refactor Subscription Handling to new subscription classes.

---

clkmgr/proxy/connect_chrony.cpp

Improve the connection handling mechanism in the Chrony connection manager by tracking connection status more explicitly and restructuring the reconnection logic for better reliability.
This patch:
- Adds a lost_connection flag to explicitly track connection state
- Improves initial connection error handling
- Prevents subscription attempts and lead to proxy crash when there is no active connection
- Makes error messages more specific to differentiate between initial connection failures and connection loss during operation

clkmgr: Fix Chrony connection handling

---

clkmgr/client/timebase_configs.cpp
clkmgr/common/timebase.hpp
clkmgr/proxy/config_parser.cpp
clkmgr/pub/clkmgr/timebase_configs.h
clkmgr/sample/clkmgr_test.cpp
clkmgr/utest/timebase_configs.cpp

<h1>Suggested PR Title - Enhance Clock Subscription Management and Configuration Flags Handling in clkmgr</h1>
This commit refactors the handling of clock subscriptions by introducing a vector of `ClockSyncSubscription` objects, allowing for more flexible and scalable management of subscriptions.
- Added `haveSys` and `havePtp` flags to `TimeBaseCfg` to track system and PTP configurations.
- Updated `TimeBaseConfigurations::addTimeBaseCfg` to set `m_have_sys` and `m_have_ptp` based on the new flags.
- Modified `JsonConfigParser::process_json` to correctly set `haveSys` and `havePtp` flags during configuration parsing.
- Changed `TimeBaseRecord` default values for `m_have_ptp` and `m_have_sys` to `false` to reflect the new configuration logic.
- Introduced a vector `overallSub` in …

clkmgr: Refactor subscription handling.

---

clkmgr/utest/Makefile
clkmgr/utest/clockmanager.cpp

<h1>Suggested PR Title - Add Comprehensive Unit Tests for ClockManager API and Update Makefile for Test Compilation</h1>
Add unit test for API in clkmgr/pub/clockmanager.h
create_tests
___
- Added extensive unit tests for the ClockManager class in clkmgr/utest/clockmanager.cpp, covering various methods and scenarios including connection, disconnection, and subscription processes.
- Updated the Makefile in clkmgr/utest/ to support the compilation and execution of the new unit tests for the ClockManager API.
___
<table><thead><tr><th>Filename&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

clkmgr: Add unit test for pub API.

---

Makefile
clkmgr/Makefile
clkmgr/TEST_clkmgr.md
clkmgr/client/clkmgr.i
clkmgr/client/clockmanager.cpp
clkmgr/client/clockmanager_c.cpp
clkmgr/client/subscription.cpp
clkmgr/client/timebase_state.cpp
clkmgr/common/msgq_tport.cpp
clkmgr/common/msgq_tport.hpp
clkmgr/common/types.m4
clkmgr/proxy/client.cpp
clkmgr/proxy/client.hpp
clkmgr/proxy/clkmgr-proxy.service
clkmgr/proxy/clkmgr-proxy.socket
clkmgr/proxy/main.cpp
clkmgr/pub/clkmgr/subscription.h
clkmgr/sample/clkmgr_c_test.c
clkmgr/sample/clkmgr_test.cpp
clkmgr/utest/clockmanager.cpp
clkmgr/utest/subscription.cpp
wrappers/perl/clkmgr_test.pl
wrappers/python/clkmgr_test.py
wrappers/ruby/clkmgr_test.rb
wrappers/ruby/warn.i

<h1>Suggested PR Title - Enhance event handling, message queue access, and add comprehensive test scripts</h1>
Tested functionality:
code_enhancement, feature_enhancement
___
- Updated various files to use new event naming conventions and improved logic for event handling.
- Enhanced message queue handling by allowing all user access and increasing buffer sizes.
- Added new command-line options to control message queue access.
- Added comprehensive test scripts in Perl and Python for the Clock Manager client.
___
<table><thead><tr><th>Filename&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Add Erez's patches

---

clkmgr/proxy/config_parser.cpp
clkmgr/utest/Makefile
clkmgr/utest/config_parser.cpp

Changed List:
- clkmgr: Clear timeBaseCfgs before parsing new JSON config
- clkmgr: Add unit test for Json config parser

clkmgr: Unit test for Json config parser

---

clkmgr/TEST_clkmgr.md
clkmgr/client/clockmanager.cpp
clkmgr/client/clockmanager_c.cpp
clkmgr/common/types.m4
clkmgr/pub/clkmgr/clockmanager_c.h
clkmgr/pub/clockmanager.h
clkmgr/sample/clkmgr_c_test.c
clkmgr/sample/clkmgr_test.cpp
clkmgr/utest/Makefile
debian/Dockerfile
gentoo/Dockerfile.1
rpm/Dockerfile
wrappers/perl/clkmgr_test.pl
wrappers/php/clkmgr_test.php
wrappers/python/clkmgr_test.py
wrappers/ruby/clkmgr_test.rb
wrappers/tcl/clkmgr_test.tcl
wrappers/tcl/pkgIndex_tcl.sh

<h1>Suggested PR Title - Enhance type safety and documentation in clkmgr module, and update dependencies in Dockerfiles</h1>
Tested with C/C++ sample apps:
code_enhancement, code_improvement
___
- Refactored various functions across C++ and C interfaces in the clkmgr module to use enums for return types, enhancing type safety and readability.
- Updated sample applications and test scripts in multiple languages to align with the new enum types and improved error handling.
- Enhanced documentation and usage messages in test scripts and markdown files to provide clearer instructions.
- Modified Dockerfiles across different distributions to …

Add patch from Erez

---

clkmgr/client/clock_event.cpp
clkmgr/client/subscription.cpp
clkmgr/common/types.m4
clkmgr/pub/clkmgr/event_c.h
clkmgr/pub/clkmgr/subscription_c.h

<h1>Suggested PR Title - Refactor Clkmgr Clock Type Parameters to Use Enum and Optimize Memory Usage</h1>
- Changed the underlying type of the ClockType enum to `uint8_t`.
- Updated function signatures to use `enum Clkmgr_ClockType` for clock type parameters.
Tested with C/C++ sample apps:
code_enhancement, code_improvement
___
- Included types_c.h in clock_event.cpp and subscription.cpp to access the Clkmgr_ClockType enum.
- Updated various function parameters across multiple files (clock_event.cpp, subscription.cpp, event_c.h, subscription_c.h) from uint32_t to enum Clkmgr_ClockType to enhance type safety and readability.
- Changed the …

clkmgr: Refactor clock type parameters to use Clkmgr_ClockType enum

---

clkmgr/client/clock_event.cpp
clkmgr/common/types.m4
clkmgr/pub/clkmgr/event.h
clkmgr/pub/clkmgr/event_c.h
clkmgr/pub/clkmgr/timebase_configs.h
clkmgr/pub/clkmgr/timebase_configs_c.h

<h1>Suggested PR Title - Refactor syncInterval to uint64_t and Remove Unused Enum Entry</h1>
- Changed the type of syncInterval to ensure synchronization intervals are represented as non-negative values.
- Removed the unused Nm(ClockLast) entry from the ClockType enum
Tested with C/C++ sample application:
code_enhancement
___
- Changed the return type of getSyncInterval() from int64_t to uint64_t in multiple files to ensure synchronization intervals are represented as non-negative values.
- Removed the unused Nm(ClockLast) entry from the ClockType enum in event.h and types.m4.
- Updated documentation in timebase_configs.h and …

clkmgr: Refactor syncInterval type to uint64_t

---

.github/workflows/build_gentoo2.yml
archlinux/Dockerfile
clkmgr/TEST_clkmgr.md
clkmgr/client/client_state.hpp
clkmgr/client/connect_msg.cpp
clkmgr/client/subscribe_msg.cpp
clkmgr/client/timebase_state.cpp
clkmgr/common/types.m4
clkmgr/proxy/connect_msg.cpp
clkmgr/proxy/connect_ptp4l.cpp
clkmgr/sample/clkmgr_c_test.c
clkmgr/sample/clkmgr_test.cpp
clkmgr/utest/clockmanager.cpp
debian/make_docker.sh
gentoo/Dockerfile
gentoo/Dockerfile.1
rpm/Dockerfile
rpm/make_docker.sh
wrappers/go/clkmgr_gtest/clkmgr_gtest.go
wrappers/lua/clkmgr_test.lua
wrappers/perl/clkmgr_test.pl
wrappers/php/clkmgr_test.php
wrappers/python/clkmgr_test.py
wrappers/ruby/clkmgr_test.rb
wrappers/tcl/clkmgr_test.tcl

<h1>Suggested PR Title - Update Event Mask Enum Values and Improve Documentation and Test Scripts</h1>
code_enhancement, feature_enhancement
___
- Updated event mask enum values across multiple files for clarity.
- Removed redundant inline comments and updated documentation comments from @brief to regular comments in several files.
- Made global variables static in test samples and improved handling of non-printable characters in output.
- Added libsystemd-dev and systemd-devel to Docker setup scripts for Debian and RPM.
- Updated test scripts in various languages to use the new event mask enum values.
- Added a conditional check in the …

Update event mask enum and remove @brief for doxygen

---

clkmgr/pub/clkmgr/event.h
clkmgr/utest/client_state.cpp
clkmgr/utest/clockmanager.cpp
clkmgr/utest/event.cpp

<h1>Suggested PR Title - Enhance clkmgr Unit Tests and Update Default Event State Handling</h1>
Tested with:
-make utest_clkmgr
-make utest_clkmgr ClientStateTest
-make utest_clkmgr ClientStateTest.connectAndReply
-make utest_clkmgr ClientStateTest.sendMessage
-make utest_clkmgr ClockManagerTest
-make utest_clkmgr ClockManagerTest.subsribe
-make utest_clkmgr ClockManagerTest.statusWait
Output of sample apps with isOffsetInRange event is "1" when offset is 0 for both ptp and chrony:
code_enhancement, update_tests
___
- Added initialization checks in ClientStateTest to ensure ClientState is properly initialized before sending messages or …

clkmgr: Fix unit test isolation issues and default event state.

---

clkmgr/proxy/connect_ptp4l.cpp

- `ptp_isSyncedWithGm` shows 0 when `clkmgr_proxy` starts after `ptp4l` is already synced.
- Adds a check to ensure the port data set is only reset when the gmIdentity actually changes, preventing unnecessary resets and ensuring correct sync status reporting.
Results:
C++:
C:

clkmgr: Fix ptp_isSyncedWithGm to reflect properly

---

clkmgr/clkmgr_proxy_cfg.md

Correct the man page title and NAME section from "PROXY_CFG" and "proxy_cfg" to "CLKMGR_PROXY_CFG" and "clkmgr_proxy_cfg" for consistency with the actual file name.

clkmgr: Fix clkmgr_proxy_cfg man file name mismatch
